(define (my-equal? a b)
  (cond ((and (not (pair? a))
              (not (pair? b)))
         (eq? a b))
        ((or (and (pair? a) (not (pair? b)))
             (and (pair? b) (not (pair? a))))
         #f)
        (else (and (my-equal? (car a) (car b))
                   (my-equal? (cdr a) (cdr b))))))
