;; The sine of an angle can be computed by making use of the approximation
;; sinx ≅ x if x is sufficiently small.


(define (sine angle)
  (define (p x) (- (* 3 x) (* 4 (cube x))))
  (define (cube x) (* x x x))
  (if (not (> (abs angle) 0.1))
      angle
      (p (sine (/ angle 3.0)))))

;; a. How many times is the procedure p applied
;; when (sine 12.15) is evaluated?

;; 5 times.

;; b. What is the order of growth in space and number of steps (as a
;; function of a) used by the process generated by the sine
;; procedure when (sine a) is evaluated?

;; Since each time a is divided by 3, it is a kind of logarithm decrease. The order of growth in time is O(log n).

;; Each time the procedure p is called the register needs to remember the value of a. 
;; Therefore, as "a" decreases in logarithm 
